### ISSUE TITLE
Update matching the 1.19.2 chunk-system

### ISSUE THREAD

**Issue by voidpointer0x00** [PaperMC/docs#112]
https://github.com/PaperMC/docs/blob/8ff2e03bf8405bcd3656b26fcb19f398898c83ca/docs/paper/admin/reference/global-configuration.md?plain=1#L15-L24

This configuration section was removed somewhere in the middle of 1.19-1.19.2, I believe here https://github.com/PaperMC/Paper/commit/01a13871deefa50e186a10b63f71c5e0459e7d30

And the new one was introduced:
```yaml
chunk-system:
  gen-parallelism: default # what are other options?
  io-threads: -1 # does it affect load&save chunk operations?
  worker-threads: -1 # what does one worker do?
```
