### ISSUE TITLE
Document bukkit.yml's worlds section

### ISSUE THREAD

**Issue by Warriorrrr** [PaperMC/docs#258]
The bukkit.yml has an optional worlds section that currently isn't documented, it's used for changing the generator/biome provider for specific worlds to ones from plugins

Example:
```yml
worlds:
  world:
    generator: pluginname:generator
    biome-provider: pluginname:biomeprovider
```
