### ISSUE TITLE
paper-world-defaults.yml's door-breaking-difficulty field doesn't match the one created by paper server

### ISSUE THREAD

**Issue by Privatech38** [PaperMC/docs#587]
https://github.com/PaperMC/docs/blob/79db3f777af4f881e65f657a7219ee9fbfcf1a38/src/config/paper/paper-world-defaults.yml#L201-L205

Which creates the following:
```yml
door-breaking-difficulty:
 - HARD
 - NORMAL
 - EASY
 - PEACEFUL
```

But the paper server generated one looks as follows:
```yml
door-breaking-difficulty:
  husk:
  - HARD
  vindicator:
  - NORMAL
  - HARD
  zombie:
  - HARD
  zombie_villager:
  - HARD
  zombified_piglin:
  - HARD
```

@Lulu13022002 mentioned in discord that it would be best to just mimic the `despawn-time` section
